<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>79c5c621-055f-4f8e-8fde-161f11bec1b8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EdgeLogger.ServiceDefaults\EdgeLogger.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="NATS.Net" Version="2.7.1" />
  </ItemGroup>

</Project>
